# Generated by Django 5.2.17 on 2026-09-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0003_organizacao_dias_lead_parado"),
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("estoque_atual", models.PositiveIntegerField(default=0)),
                (
                    "estoque_minimo",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Abaixo disso, o produto aparece como estoque baixo/crítico na Visão geral.",
                    ),
                ),
                (
                    "duracao_estimada_dias",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Quantos dias uma unidade dura em uso — usado pra prever quando a paciente vai precisar recomprar. Deixe em branco se não se aplica.",
                        null=True,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto",
                "verbose_name_plural": "produtos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="ProducaoPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGUARDANDO_INICIO", "Aguardando início"),
                            ("EM_ANDAMENTO", "Em manipulação"),
                            ("PRONTO", "Pronto"),
                        ],
                        default="AGUARDANDO_INICIO",
                        max_length=20,
                    ),
                ),
                ("previsao_conclusao", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producoes",
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "produção pendente",
                "verbose_name_plural": "produções pendentes",
                "ordering": ["previsao_conclusao"],
            },
        ),
        migrations.CreateModel(
            name="Recompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_prevista", models.DateField()),
                ("data_realizada", models.DateField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recompras",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recompras",
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "recompra",
                "verbose_name_plural": "recompras",
                "ordering": ["data_prevista"],
            },
        ),
    ]
