# Generated by Django 5.2.17 on 2026-09-23 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0008_organizacao_meta_consultas_mensal_and_more"),
        ("estoque", "0001_initial"),
        ("pacientes", "0004_historicofechamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="preco_cartao",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Usado para sugerir o valor ao registrar uma venda — pode ser ajustado na hora.",
                max_digits=8,
                verbose_name="preço no cartão",
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_pix",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Usado para sugerir o valor ao registrar uma venda — pode ser ajustado na hora.",
                max_digits=8,
                verbose_name="preço no Pix/dinheiro",
            ),
        ),
        migrations.CreateModel(
            name="VendaProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[("PIX", "Pix/dinheiro"), ("CARTAO", "Cartão")],
                        default="PIX",
                        max_length=10,
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_produtos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendas",
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "venda de produto",
                "verbose_name_plural": "vendas de produtos",
                "ordering": ["-data", "-criado_em"],
            },
        ),
    ]
