# Generated by Django 5.2.17 on 2026-09-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0002_produto_preco_cartao_produto_preco_pix_vendaproduto"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendaproduto",
            name="nome_comprador_avulso",
            field=models.CharField(
                blank=True,
                help_text="Pra quem só quer comprar o produto, sem ser paciente — não cria cadastro nenhum.",
                max_length=150,
                verbose_name="nome (quem não é paciente cadastrada)",
            ),
        ),
    ]
