# Generated by Django 5.2.17 on 2026-09-24 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0008_organizacao_meta_consultas_mensal_and_more"),
        ("estoque", "0003_vendaproduto_nome_comprador_avulso"),
        ("pacientes", "0004_historicofechamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_comprador_avulso",
                    models.CharField(
                        blank=True,
                        help_text="Pra quem só quer comprar o produto, sem ser paciente — não cria cadastro nenhum.",
                        max_length=150,
                        verbose_name="nome (quem não é paciente cadastrada)",
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[("PIX", "Pix/dinheiro"), ("CARTAO", "Cartão")],
                        default="PIX",
                        help_text="Usada pra calcular o preço de cada item (tabela Pix ou cartão) no momento da venda.",
                        max_length=10,
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compras_produtos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "venda",
                "verbose_name_plural": "vendas",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_vendidos",
                        to="estoque.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "item da venda",
                "verbose_name_plural": "itens da venda",
            },
        ),
    ]
