# Generated by Django 5.2.17 on 2026-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0005_migrar_vendaproduto_para_venda"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Pra indicação, presente ou qualquer outro desconto combinado — anote o motivo em Observações.",
                max_digits=10,
            ),
        ),
    ]
