# Generated by Django 5.2.17 on 2026-09-13 19:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="nome do paciente"),
                ),
                ("whatsapp", models.CharField(max_length=20)),
                ("telefone", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("PAUSADO", "Pausado"),
                            ("AGENDADA", "Agendada"),
                            ("SEM_RESPOSTA", "Sem resposta"),
                            ("PERDIDA", "Perdida"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("NOVO", "Novo / pendente"),
                            ("CONTATO_1", "1º contato"),
                            ("CONTATO_2", "2º contato"),
                            ("CONTATO_3", "3º contato — prova social"),
                            ("CONTATO_4", "4º contato — encerramento"),
                            ("CONCLUIDA", "Cadência concluída"),
                        ],
                        default="NOVO",
                        max_length=20,
                    ),
                ),
                (
                    "tentativas_etapa_atual",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Quantas tentativas de contato já foram feitas na etapa atual (reinicia a cada nova etapa).",
                    ),
                ),
                (
                    "entrou_em",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="data/hora de entrada",
                    ),
                ),
                ("ultimo_contato_em", models.DateTimeField(blank=True, null=True)),
                ("proxima_acao", models.CharField(blank=True, max_length=255)),
                (
                    "proxima_acao_em",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quando a próxima ação deve acontecer (usado na fila do dia).",
                        null=True,
                    ),
                ),
                (
                    "perdido_detalhe",
                    models.TextField(
                        blank=True,
                        help_text="Preenchido quando o motivo de perda é 'Outro'.",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Preenchido automaticamente quando a consulta é agendada.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lead",
                "verbose_name_plural": "leads",
                "ordering": ["-entrou_em"],
            },
        ),
        migrations.CreateModel(
            name="HistoricoLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada do lead"),
                            ("LIGACAO", "Ligação"),
                            ("WHATSAPP", "WhatsApp"),
                            ("RESPOSTA", "Resposta do lead"),
                            ("STATUS", "Mudança de status/etapa"),
                            ("PAUSA", "Cadência pausada"),
                            ("RETOMADA", "Cadência retomada"),
                            ("AGENDAMENTO", "Consulta agendada"),
                            ("PERDA", "Lead perdida"),
                            ("NOTA", "Observação"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(max_length=500)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico",
                        to="leads.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico do lead",
                "verbose_name_plural": "histórico dos leads",
                "ordering": ["-data_hora"],
            },
        ),
        migrations.CreateModel(
            name="MensagemModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "etapa",
                    models.CharField(
                        choices=[
                            ("CONTATO_1", "1º contato"),
                            ("CONTATO_2", "2º contato"),
                            ("CONTATO_3", "3º contato — prova social"),
                            ("CONTATO_4", "4º contato — encerramento"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "texto",
                    models.TextField(
                        help_text="Use {nome} para inserir o nome do lead automaticamente."
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "mensagem-modelo",
                "verbose_name_plural": "mensagens-modelo",
                "ordering": ["etapa"],
            },
        ),
        migrations.CreateModel(
            name="MotivoPerda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "motivo de perda",
                "verbose_name_plural": "motivos de perda",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="perdido_motivo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leads.motivoperda",
            ),
        ),
        migrations.CreateModel(
            name="Origem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "origem do lead",
                "verbose_name_plural": "origens do lead",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="origem",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="leads",
                to="leads.origem",
            ),
        ),
        migrations.CreateModel(
            name="PausaLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(max_length=255)),
                ("data_retomada_prevista", models.DateField()),
                ("observacao", models.TextField(blank=True)),
                ("retomado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pausas",
                        to="leads.lead",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "pausa de cadência",
                "verbose_name_plural": "pausas de cadência",
                "ordering": ["-criada_em"],
            },
        ),
        migrations.CreateModel(
            name="ProvaSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_interno", models.CharField(max_length=150)),
                (
                    "foto_antes",
                    models.ImageField(blank=True, upload_to="provas_sociais/antes/"),
                ),
                (
                    "foto_depois",
                    models.ImageField(blank=True, upload_to="provas_sociais/depois/"),
                ),
                ("depoimento", models.TextField(blank=True)),
                (
                    "texto_sugerido",
                    models.TextField(
                        blank=True,
                        help_text="Texto sugerido para acompanhar o envio no WhatsApp.",
                    ),
                ),
                (
                    "autorizacao_uso_imagem",
                    models.BooleanField(
                        default=False,
                        verbose_name="autorização de uso de imagem registrada",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "prova social",
                "verbose_name_plural": "provas sociais",
                "ordering": ["nome_interno"],
            },
        ),
        migrations.AddConstraint(
            model_name="motivoperda",
            constraint=models.UniqueConstraint(
                fields=("organizacao", "nome"),
                name="motivo_perda_unico_por_organizacao",
            ),
        ),
        migrations.AddConstraint(
            model_name="origem",
            constraint=models.UniqueConstraint(
                fields=("organizacao", "nome"), name="origem_unica_por_organizacao"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["organizacao", "status"], name="leads_lead_organiz_0cb2df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["organizacao", "etapa"], name="leads_lead_organiz_9383bc_idx"
            ),
        ),
    ]
