# Generated by Django 5.2.17 on 2026-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="cidade",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lead",
            name="estado",
            field=models.CharField(
                blank=True,
                help_text="Sigla do estado, ex.: SP, RJ, MG.",
                max_length=2,
                verbose_name="estado (UF)",
            ),
        ),
    ]
