# Generated by Django 5.2.17 on 2026-09-14 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_organizacao_padrao_e_dados_iniciais"),
        ("leads", "0002_lead_cidade_lead_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookImportacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("ativo", models.BooleanField(default=True)),
                ("total_recebidos", models.PositiveIntegerField(default=0)),
                ("total_duplicados", models.PositiveIntegerField(default=0)),
                ("ultimo_recebido_em", models.DateTimeField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "origem_padrao",
                    models.ForeignKey(
                        help_text="Origem atribuída aos leads recebidos por aqui quando o envio não informar uma.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhooks_importacao",
                        to="leads.origem",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook de importação de leads",
                "verbose_name_plural": "webhooks de importação de leads",
            },
        ),
    ]
