# Generated by Django 5.2.17 on 2026-09-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_origens_quiz_e_plano_alimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="dados_formulario",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Respostas extras recebidas junto com o lead (ex.: quiz/formulário externo) que não têm um campo próprio — guardadas aqui só pra exibir na ficha do lead.",
            ),
        ),
    ]
