# Generated by Django 5.2.17 on 2026-09-22 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0007_usuario_comissao_fixo_mensal_and_more"),
        ("leads", "0005_lead_dados_formulario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroSocialSelling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "seguidores_novos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="seguidores novos"
                    ),
                ),
                (
                    "pessoas_chamadas",
                    models.PositiveIntegerField(
                        default=0, verbose_name="pessoas chamadas no Instagram"
                    ),
                ),
                (
                    "pessoas_responderam",
                    models.PositiveIntegerField(
                        default=0, verbose_name="pessoas que responderam"
                    ),
                ),
                (
                    "contatos_conseguidos",
                    models.PositiveIntegerField(
                        default=0, verbose_name="telefones conseguidos"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registros_social_selling",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de social selling",
                "verbose_name_plural": "registros de social selling",
                "ordering": ["-data"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "data"), name="social_selling_unico_por_dia"
                    )
                ],
            },
        ),
    ]
