# Generated by Django 5.2.17 on 2026-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_registrosocialselling"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="instagram",
            field=models.CharField(
                blank=True,
                help_text="@ do Instagram — usado pra abordagem direta por lá, antes de conseguir o telefone.",
                max_length=100,
                verbose_name="usuário do Instagram",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="whatsapp",
            field=models.CharField(
                blank=True,
                help_text="Pode ficar em branco enquanto o único contato é pelo Instagram.",
                max_length=20,
            ),
        ),
    ]
