# Generated by Django 5.2.17 on 2026-09-23 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0008_organizacao_meta_consultas_mensal_and_more"),
        ("leads", "0007_lead_instagram_alter_lead_whatsapp"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroMarketingDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "investimento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "impressoes",
                    models.PositiveIntegerField(default=0, verbose_name="impressões"),
                ),
                ("cliques", models.PositiveIntegerField(default=0)),
                (
                    "pageviews",
                    models.PositiveIntegerField(default=0, verbose_name="pageviews"),
                ),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro diário de marketing",
                "verbose_name_plural": "registros diários de marketing",
                "ordering": ["-data"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organizacao", "data"),
                        name="marketing_diario_unico_por_dia",
                    )
                ],
            },
        ),
    ]
