# Generated by Django 5.2.17 on 2026-09-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profissional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="nome completo"),
                ),
                ("especialidade", models.CharField(blank=True, max_length=100)),
                (
                    "registro_conselho",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: CRM, COREN, CRO, etc.",
                        max_length=50,
                        verbose_name="registro no conselho de classe",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "profissional",
                "verbose_name_plural": "profissionais",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="HorarioAtendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.IntegerField(
                        choices=[
                            (0, "Segunda-feira"),
                            (1, "Terça-feira"),
                            (2, "Quarta-feira"),
                            (3, "Quinta-feira"),
                            (4, "Sexta-feira"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        verbose_name="dia da semana",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="início")),
                ("hora_fim", models.TimeField(verbose_name="fim")),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="horarios",
                        to="profissionais.profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "horário de atendimento",
                "verbose_name_plural": "horários de atendimento",
                "ordering": ["profissional", "dia_semana", "hora_inicio"],
            },
        ),
    ]
