# Generated by Django 5.2.17 on 2026-09-13 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0002_initial"),
        ("contas", "0001_initial"),
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acompanhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("data_termino_prevista", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EM_ACOMPANHAMENTO", "Em acompanhamento"),
                            ("MANUTENCAO", "Em manutenção"),
                            ("AGUARDANDO_DECISAO", "Aguardando decisão"),
                            ("RENOVADO", "Renovado"),
                            ("MIGRADO", "Migrado para outro programa"),
                            ("FINALIZADO", "Finalizado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="EM_ACOMPANHAMENTO",
                        max_length=25,
                    ),
                ),
                (
                    "valor_contratado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "desconto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("forma_pagamento", models.CharField(blank=True, max_length=100)),
                ("modulacao_concluida", models.BooleanField(default=False)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acompanhamentos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "acompanhamento",
                "verbose_name_plural": "acompanhamentos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="CustoAcompanhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "acompanhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custos",
                        to="programas.acompanhamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "custo do acompanhamento",
                "verbose_name_plural": "custos do acompanhamento",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("duracao_meses", models.PositiveIntegerField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "valor_a_vista",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("parcelamento_max", models.PositiveIntegerField(default=12)),
                ("qtd_consultas", models.PositiveIntegerField(default=1)),
                ("qtd_modulacoes", models.PositiveIntegerField(default=1)),
                ("qtd_kits", models.PositiveIntegerField(default=1)),
                (
                    "produtos_incluidos",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: 1 produto para o dia + 1 produto para a noite por kit.",
                        max_length=255,
                    ),
                ),
                (
                    "horario_suporte",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: Segunda a sexta-feira, das 09:00 às 18:00.",
                        max_length=150,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "programa de acompanhamento",
                "verbose_name_plural": "programas de acompanhamento",
                "ordering": ["duracao_meses"],
            },
        ),
        migrations.AddField(
            model_name="acompanhamento",
            name="programa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="acompanhamentos",
                to="programas.programa",
            ),
        ),
        migrations.CreateModel(
            name="ConsultaPrevista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE_AGENDAMENTO", "Pendente de agendamento"),
                            ("AGENDADA", "Agendada"),
                            ("REALIZADA", "Realizada"),
                            ("REAGENDADA", "Reagendada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDENTE_AGENDAMENTO",
                        max_length=25,
                    ),
                ),
                (
                    "acompanhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultas_previstas",
                        to="programas.acompanhamento",
                    ),
                ),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agenda.consulta",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta prevista",
                "verbose_name_plural": "consultas previstas",
                "ordering": ["numero"],
                "unique_together": {("acompanhamento", "numero")},
            },
        ),
        migrations.CreateModel(
            name="KitPrevisto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDENTE", "Pendente"), ("ENVIADO", "Enviado")],
                        default="PENDENTE",
                        max_length=10,
                    ),
                ),
                ("data_envio", models.DateField(blank=True, null=True)),
                (
                    "acompanhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kits_previstos",
                        to="programas.acompanhamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "kit previsto",
                "verbose_name_plural": "kits previstos",
                "ordering": ["numero"],
                "unique_together": {("acompanhamento", "numero")},
            },
        ),
    ]
