# Generated by Django 5.2.17 on 2026-09-15 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="acompanhamento",
            name="modulacao_concluida",
        ),
        migrations.CreateModel(
            name="Modulacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "acompanhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modulacoes",
                        to="programas.acompanhamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "modulação",
                "verbose_name_plural": "modulações",
                "ordering": ["numero"],
                "unique_together": {("acompanhamento", "numero")},
            },
        ),
        migrations.CreateModel(
            name="FaseModulacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField(help_text="1, 2 ou 3.")),
                ("duracao_semanas", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("EM_ANDAMENTO", "Em andamento"),
                            ("CONCLUIDA", "Concluída"),
                        ],
                        default="PENDENTE",
                        max_length=15,
                    ),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_prevista", models.DateField(blank=True, null=True)),
                (
                    "plano",
                    models.TextField(
                        blank=True, help_text="O que foi prescrito pra essa fase."
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MELHOROU", "Melhorou"),
                            ("PERMANECE", "Permanece"),
                            ("PIOROU", "Piorou"),
                        ],
                        max_length=15,
                    ),
                ),
                ("principais_melhoras", models.TextField(blank=True)),
                (
                    "o_que_trabalhar",
                    models.TextField(
                        blank=True, help_text="Alimenta o plano da próxima fase."
                    ),
                ),
                ("avaliado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "modulacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fases",
                        to="programas.modulacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "fase da modulação",
                "verbose_name_plural": "fases da modulação",
                "ordering": ["numero"],
                "unique_together": {("modulacao", "numero")},
            },
        ),
    ]
