# Generated by Django 5.2.17 on 2026-09-15 20:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "programas",
            "0002_remove_acompanhamento_modulacao_concluida_modulacao_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "semana",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Semana da fase a que o relato se refere, se houver.",
                        null=True,
                    ),
                ),
                ("relato", models.TextField(verbose_name="relato da paciente")),
                (
                    "observacao",
                    models.TextField(
                        blank=True, verbose_name="observação do profissional"
                    ),
                ),
                ("conduta", models.TextField(blank=True)),
                (
                    "precisou_alterar",
                    models.BooleanField(
                        default=False,
                        verbose_name="precisou alterar o plano por causa desse feedback?",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "acompanhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="programas.acompanhamento",
                    ),
                ),
                (
                    "fase",
                    models.ForeignKey(
                        blank=True,
                        help_text="Fase da modulação a que esse feedback se refere, se houver.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="programas.fasemodulacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "feedback",
                "verbose_name_plural": "feedbacks",
                "ordering": ["-data_hora"],
            },
        ),
    ]
