# Generated by Django 5.2.17 on 2026-09-15 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0003_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="acompanhamento",
            name="status_atualizado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Quando o status mudou pela última vez (pra linha do tempo).",
                null=True,
            ),
        ),
    ]
