# Generated by Django 5.2.17 on 2026-09-15 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0004_acompanhamento_status_atualizado_em"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoEvolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "angulo",
                    models.CharField(
                        choices=[
                            ("FRONTAL", "Frontal"),
                            ("LATERAL_DIREITA", "Lateral direita"),
                            ("LATERAL_ESQUERDA", "Lateral esquerda"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "momento",
                    models.CharField(
                        choices=[
                            ("INICIO", "Início"),
                            ("MEIO", "Meio"),
                            ("FINAL", "Final"),
                        ],
                        max_length=10,
                    ),
                ),
                ("imagem", models.ImageField(upload_to="fotos_evolucao/%Y/%m/")),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "acompanhamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos",
                        to="programas.acompanhamento",
                    ),
                ),
                (
                    "enviada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "foto de evolução",
                "verbose_name_plural": "fotos de evolução",
                "ordering": ["angulo", "momento", "-criado_em"],
            },
        ),
    ]
