# Generated by Django 5.2.17 on 2026-09-16 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
        ("programas", "0005_fotoevolucao"),
    ]

    operations = [
        migrations.CreateModel(
            name="KitProdutoItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "kit_previsto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="programas.kitprevisto",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "produto do kit",
                "verbose_name_plural": "produtos do kit",
            },
        ),
    ]
