# Generated by Django 5.2.17 on 2026-09-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0006_kitprodutoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitprevisto",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("ENVIADO", "Enviado"),
                    ("NAO_SE_APLICA", "Não se aplica"),
                ],
                default="PENDENTE",
                max_length=15,
            ),
        ),
    ]
