# Generated by Django 5.2.17 on 2026-09-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programas", "0007_alter_kitprevisto_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="programa",
            name="intervalo_dias_consultas",
            field=models.PositiveIntegerField(
                default=60,
                help_text="Quantos dias esperar, depois da consulta anterior, antes de alertar que é hora de agendar a próxima.",
            ),
        ),
    ]
