# Generated by Django 5.2.17 on 2026-10-06 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0009_organizacao_limite_fila_fechamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="VendaKitMentora",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kit_nome", models.CharField(max_length=150, verbose_name="kit")),
                ("quantidade", models.PositiveIntegerField(default=1)),
                (
                    "valor_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor por kit"
                    ),
                ),
                ("data_venda", models.DateField()),
                (
                    "valor_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "data_pagamento_restante",
                    models.DateField(
                        blank=True,
                        help_text="Quando o saldo (se houver) deve ser pago.",
                        null=True,
                    ),
                ),
                (
                    "previsao_proxima_compra",
                    models.DateField(
                        blank=True,
                        help_text="Pra quando você espera que essa mentorada precise comprar de novo.",
                        null=True,
                    ),
                ),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "mentorada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras_kit_mentora",
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "venda de kit pra mentorada",
                "verbose_name_plural": "vendas de kit pras mentoradas",
                "ordering": ["-data_venda", "-criado_em"],
            },
        ),
    ]
