# Generated by Django 5.2.17 on 2026-10-06 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0009_organizacao_limite_fila_fechamento"),
        ("core", "0003_vendakitmentora_produtos_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoMentoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor total combinado com essa mentorada (ex.: R$ 30.000).",
                        max_digits=10,
                        verbose_name="valor total da mentoria",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "mentorada",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrato_mentoria",
                        to="contas.organizacao",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        help_text="Organização que está vendendo a mentoria — normalmente a sua própria.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contratos_mentoria_como_fornecedora",
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "contrato de mentoria",
                "verbose_name_plural": "contratos de mentoria",
                "ordering": ["mentorada__nome"],
            },
        ),
        migrations.CreateModel(
            name="ParcelaMentoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "data_prevista",
                    models.DateField(
                        blank=True,
                        help_text="Quando você espera receber esse valor. Pode deixar em branco se já foi pago.",
                        null=True,
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateField(
                        blank=True,
                        help_text="Preencha quando o valor realmente entrar. Deixe em branco pra lançar como previsão futura.",
                        null=True,
                    ),
                ),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parcelas",
                        to="core.contratomentoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "parcela de mentoria",
                "verbose_name_plural": "parcelas de mentoria",
                "ordering": ["-criado_em"],
            },
        ),
    ]
