# Generated by Django 5.2.17 on 2026-09-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="data e hora")),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        default=30, verbose_name="duração (min)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("REALIZADA", "Realizada"),
                            ("REAGENDADA", "Reagendada"),
                            ("CANCELADA", "Cancelada"),
                            ("NAO_COMPARECEU", "Não compareceu"),
                        ],
                        default="AGENDADA",
                        max_length=20,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="motivo da consulta"
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "consulta",
                "verbose_name_plural": "consultas",
                "ordering": ["data_hora"],
            },
        ),
        migrations.CreateModel(
            name="HorarioBloqueado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField()),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("ALMOCO", "Horário de almoço"),
                            ("REUNIAO", "Reunião"),
                            ("COMPROMISSO_PESSOAL", "Compromisso pessoal"),
                            ("TREINAMENTO", "Treinamento"),
                            ("FERIAS", "Férias"),
                            ("SEM_ATENDIMENTO", "Dia sem atendimento"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=25,
                    ),
                ),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("cor", models.CharField(default="#EF4444", max_length=7)),
            ],
            options={
                "verbose_name": "horário bloqueado",
                "verbose_name_plural": "horários bloqueados",
                "ordering": ["inicio"],
            },
        ),
        migrations.CreateModel(
            name="TipoConsulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                (
                    "cor",
                    models.CharField(
                        default="#7C3AED",
                        help_text="Cor em hexadecimal usada nos blocos e na legenda da agenda. Ex.: #7C3AED",
                        max_length=7,
                    ),
                ),
                ("duracao_padrao_minutos", models.PositiveIntegerField(default=30)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "tipo de consulta",
                "verbose_name_plural": "tipos de consulta",
                "ordering": ["ordem", "nome"],
            },
        ),
    ]
