# Generated by Django 5.2.17 on 2026-09-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(verbose_name="data e hora")),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        default=30, verbose_name="duração (min)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AGENDADA", "Agendada"),
                            ("CONFIRMADA", "Confirmada"),
                            ("ATENDIDA", "Atendida"),
                            ("CANCELADA", "Cancelada"),
                            ("FALTOU", "Paciente faltou"),
                        ],
                        default="AGENDADA",
                        max_length=20,
                    ),
                ),
                (
                    "motivo",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="motivo da consulta"
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultas",
                        to="profissionais.profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "consulta",
                "verbose_name_plural": "consultas",
                "ordering": ["data_hora"],
                "indexes": [
                    models.Index(
                        fields=["profissional", "data_hora"],
                        name="agenda_cons_profiss_dac7d2_idx",
                    ),
                    models.Index(
                        fields=["paciente", "data_hora"],
                        name="agenda_cons_pacient_dd9a50_idx",
                    ),
                ],
            },
        ),
    ]
