# Generated by Django 5.2.17 on 2026-09-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("contas", "0001_initial"),
        ("leads", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Lead do CRM que originou este agendamento, se houver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultas",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contas.organizacao"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="paciente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultas",
                to="pacientes.paciente",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="profissional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultas",
                to="profissionais.profissional",
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="reagendada_de",
            field=models.ForeignKey(
                blank=True,
                help_text="Consulta original, quando esta é resultado de um reagendamento.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reagendamentos",
                to="agenda.consulta",
            ),
        ),
        migrations.AddField(
            model_name="horariobloqueado",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contas.organizacao"
            ),
        ),
        migrations.AddField(
            model_name="horariobloqueado",
            name="profissional",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloqueios",
                to="profissionais.profissional",
            ),
        ),
        migrations.AddField(
            model_name="tipoconsulta",
            name="organizacao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contas.organizacao"
            ),
        ),
        migrations.AddField(
            model_name="consulta",
            name="tipo_consulta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultas",
                to="agenda.tipoconsulta",
            ),
        ),
        migrations.AddIndex(
            model_name="horariobloqueado",
            index=models.Index(
                fields=["profissional", "inicio", "fim"],
                name="agenda_hora_profiss_31a960_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipoconsulta",
            constraint=models.UniqueConstraint(
                fields=("organizacao", "nome"),
                name="tipo_consulta_unico_por_organizacao",
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["profissional", "data_hora"],
                name="agenda_cons_profiss_dac7d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consulta",
            index=models.Index(
                fields=["paciente", "data_hora"], name="agenda_cons_pacient_dd9a50_idx"
            ),
        ),
    ]
