# Generated by Django 5.2.17 on 2026-09-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0003_corrige_cores_padrao_tipo_consulta"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoconsulta",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor cobrado nesse tipo de consulta. Ao agendar uma consulta desse tipo, esse valor entra automaticamente no Financeiro como receita prevista (pendente).",
                max_digits=10,
                null=True,
                verbose_name="valor",
            ),
        ),
    ]
