# Generated by Django 5.2.17 on 2026-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0005_valor_padrao_consulta_inicial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consulta",
            name="valor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Valor cobrado nesta consulta (pode ser diferente do valor padrão do tipo de consulta, para personalizar por paciente). Gera automaticamente a receita prevista no Financeiro; deixe em 0 para não cobrar por esta consulta.",
                max_digits=10,
                null=True,
                verbose_name="valor cobrado",
            ),
        ),
    ]
