# Generated by Django 5.2.17 on 2026-09-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0007_preenche_valor_consultas_existentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipoconsulta",
            name="conta_para_fechamento",
            field=models.BooleanField(
                default=True,
                help_text="Quando uma consulta desse tipo é realizada e a paciente ainda não tem programa ativo, ela entra na 'Fila de fechamento' da home, pedindo follow-up pra fechar a venda. Desmarque para tipos que não costumam virar programa — consulta de retorno de quem só compra produtos, consulta avulsa, etc.",
                verbose_name="conta para a fila de fechamento",
            ),
        ),
    ]
