# Generated by Django 5.2.17 on 2026-09-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="nome completo"),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True,
                        help_text="Opcional, mas evita cadastros duplicados.",
                        max_length=14,
                        null=True,
                        verbose_name="CPF",
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="data de nascimento"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                        max_length=1,
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="telefone/WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="e-mail"
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="endereço"
                    ),
                ),
                (
                    "historico_saude",
                    models.TextField(
                        blank=True,
                        help_text="Alergias, comorbidades, medicações em uso, observações gerais.",
                        verbose_name="histórico de saúde",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(
                        blank=True, verbose_name="observações administrativas"
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "paciente",
                "verbose_name_plural": "pacientes",
                "ordering": ["nome"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("cpf__isnull", False), models.Q(("cpf", ""), _negated=True)
                        ),
                        fields=("organizacao", "cpf"),
                        name="cpf_unico_por_organizacao",
                    )
                ],
            },
        ),
    ]
