# Generated by Django 5.2.17 on 2026-09-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="cidade",
            field=models.CharField(
                blank=True, help_text="Ex.: Belo Horizonte, MG", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="profissao",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
