# Generated by Django 5.2.17 on 2026-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="fechamento_descartado_em",
            field=models.DateTimeField(
                blank=True,
                help_text="Preenchido quando alguém marca que, após a consulta, a paciente decidiu não continuar — tira ela da fila de fechamento sem precisar excluir nada.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paciente",
            name="fechamento_descartado_motivo",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
