# Generated by Django 5.2.17 on 2026-09-23 00:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0003_paciente_fechamento_descartado_em_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricoFechamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_hora", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("PERDA", "Marcada como não vai continuar"),
                            ("REABERTURA", "Voltou pra fila de fechamento"),
                        ],
                        max_length=15,
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=500)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historico_fechamento",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "histórico de fechamento",
                "verbose_name_plural": "histórico de fechamentos",
                "ordering": ["-data_hora"],
            },
        ),
    ]
