# Generated by Django 5.2.17 on 2026-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0004_historicofechamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="paciente",
            name="oferta_consulta_diagnostico",
            field=models.CharField(
                blank=True,
                help_text="Anotação rápida do profissional sobre o plano/programa apresentado na consulta — ajuda a planejar uma ação de retomada pra quem ainda não decidiu.",
                max_length=255,
                verbose_name="o que foi ofertado na consulta de diagnóstico",
            ),
        ),
    ]
