# Generated by Django 5.2.17 on 2026-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_organizacao_padrao_e_dados_iniciais"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="dias_lead_parado",
            field=models.PositiveIntegerField(
                default=3,
                help_text='Quantos dias sem nenhuma atualização de status fazem um lead aparecer no card "Leads parados" da tela inicial.',
            ),
        ),
    ]
