# Generated by Django 5.2.17 on 2026-09-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_organizacao_dias_lead_parado"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="saldo_inicial_financeiro",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Saldo em caixa antes do primeiro lançamento registrado no sistema — base pro saldo acumulado do Controle Financeiro.",
                max_digits=10,
            ),
        ),
    ]
