# Generated by Django 5.2.17 on 2026-09-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0004_organizacao_saldo_inicial_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="modulo_financeiro_ativo",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para esconder o Controle Financeiro do menu dessa organização.",
                verbose_name="módulo Controle Financeiro ativo",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="modulo_leads_ativo",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para esconder o CRM de leads do menu dessa organização.",
                verbose_name="módulo CRM de leads ativo",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="modulo_programas_ativo",
            field=models.BooleanField(
                default=True,
                help_text="Desmarque para esconder Programas e o início de protocolo de acompanhamento dessa organização.",
                verbose_name="módulo Programas/Acompanhamento ativo",
            ),
        ),
    ]
