# Generated by Django 5.2.17 on 2026-09-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0005_organizacao_modulo_financeiro_ativo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="papel",
            field=models.CharField(
                choices=[
                    ("COMPLETO", "Acesso completo"),
                    ("COMERCIAL", "Comercial (Agenda + CRM de leads)"),
                ],
                default="COMPLETO",
                help_text='"Comercial" restringe esse usuário só à Agenda, ao CRM de leads e ao painel "O que fazer hoje" — o resto do sistema (ficha da paciente, prontuários, financeiro, indicadores, estoque, profissionais, programas) fica bloqueado pra ele.',
                max_length=20,
            ),
        ),
    ]
