# Generated by Django 5.2.17 on 2026-09-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0006_usuario_papel"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="comissao_fixo_mensal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text='Valor fixo por mês (relevante pra quem tem papel Comercial) — aparece no painel "O que fazer hoje" dessa pessoa.',
                max_digits=10,
                verbose_name="fixo mensal",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="comissao_por_agendamento",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Valor pago por cada consulta agendada a partir de um lead que essa pessoa trabalhou no CRM.",
                max_digits=10,
                verbose_name="comissão por agendamento",
            ),
        ),
    ]
