# Generated by Django 5.2.17 on 2026-09-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0007_usuario_comissao_fixo_mensal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="meta_consultas_mensal",
            field=models.PositiveIntegerField(
                default=25,
                help_text="Quantidade mínima de consultas cobradas no mês pra bater a meta de faturamento.",
                verbose_name="meta de consultas por mês",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="meta_faturamento_mensal",
            field=models.DecimalField(
                decimal_places=2,
                default=50000,
                help_text='Valor que a organização quer bater por mês (tratamentos fechados + consultas cobradas) — aparece no card "Meta do mês" da tela inicial.',
                max_digits=10,
                verbose_name="meta de faturamento mensal",
            ),
        ),
        migrations.AddField(
            model_name="organizacao",
            name="meta_fechamentos_mensal",
            field=models.PositiveIntegerField(
                default=8,
                help_text="Quantidade mínima de tratamentos/programas fechados no mês pra bater a meta de faturamento.",
                verbose_name="meta de fechamentos por mês",
            ),
        ),
    ]
