# Generated by Django 5.2.17 on 2026-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0008_organizacao_meta_consultas_mensal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizacao",
            name="limite_fila_fechamento",
            field=models.PositiveIntegerField(
                default=40,
                help_text="Quando a fila de fechamento (quem já fez consulta de diagnóstico e ainda não decidiu) atingir esse tanto de gente, mostra um aviso no CRM de fechamento.",
                verbose_name="alerta da fila de fechamento",
            ),
        ),
    ]
