# Generated by Django 5.2.17 on 2026-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0009_organizacao_limite_fila_fechamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="TentativaLoginFalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("username", models.CharField(blank=True, max_length=150)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "tentativa de login com senha errada",
                "verbose_name_plural": "tentativas de login com senha errada",
                "ordering": ["-criado_em"],
            },
        ),
    ]
