# Generated by Django 5.2.17 on 2026-09-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("pacientes", "0001_initial"),
        ("profissionais", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Atendimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(verbose_name="data e hora do atendimento"),
                ),
                ("queixa_principal", models.TextField(blank=True)),
                (
                    "historico_atual",
                    models.TextField(
                        blank=True, verbose_name="história da doença atual"
                    ),
                ),
                ("exame_fisico", models.TextField(blank=True)),
                ("diagnostico", models.TextField(blank=True)),
                (
                    "conduta",
                    models.TextField(
                        blank=True, verbose_name="conduta/procedimentos realizados"
                    ),
                ),
                ("prescricao", models.TextField(blank=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.OneToOneField(
                        blank=True,
                        help_text="Consulta agendada que originou este atendimento (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimento",
                        to="agenda.consulta",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "profissional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos",
                        to="profissionais.profissional",
                    ),
                ),
            ],
            options={
                "verbose_name": "atendimento",
                "verbose_name_plural": "atendimentos (prontuário)",
                "ordering": ["-data_hora"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "data_hora"],
                        name="prontuarios_pacient_07fed8_idx",
                    )
                ],
            },
        ),
    ]
