# Generated by Django 5.2.17 on 2026-09-15 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_organizacao_dias_lead_parado"),
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
        ("prontuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anamnese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "melasma_pele",
                    models.TextField(blank=True, verbose_name="melasma / pele"),
                ),
                ("intestino", models.TextField(blank=True)),
                (
                    "estomago_digestao",
                    models.TextField(blank=True, verbose_name="estômago / digestão"),
                ),
                (
                    "figado_vesicula",
                    models.TextField(blank=True, verbose_name="fígado / vesícula"),
                ),
                (
                    "hormonal_ciclo",
                    models.TextField(blank=True, verbose_name="hormonal / ciclo"),
                ),
                ("sono", models.TextField(blank=True)),
                ("alimentacao", models.TextField(blank=True)),
                ("medicamentos", models.TextField(blank=True)),
                (
                    "historico_saude",
                    models.TextField(blank=True, verbose_name="histórico de saúde"),
                ),
                (
                    "sinais_sintomas",
                    models.TextField(blank=True, verbose_name="sinais e sintomas"),
                ),
                (
                    "observacoes_profissional",
                    models.TextField(
                        blank=True, verbose_name="observações do profissional"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="anamnese",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "anamnese",
                "verbose_name_plural": "anamneses",
            },
        ),
    ]
