# Generated by Django 5.2.17 on 2026-09-15 22:10

import django.db.models.deletion
import prontuarios.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_organizacao_dias_lead_parado"),
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
        ("prontuarios", "0002_anamnese"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EXAME", "Exame"),
                            ("DOCUMENTO", "Documento"),
                            ("OUTRO", "Outro"),
                        ],
                        default="EXAME",
                        max_length=20,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        storage=prontuarios.models._storage_documento,
                        upload_to="documentos/%Y/%m/",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "exame/documento",
                "verbose_name_plural": "exames/documentos",
                "ordering": ["-criado_em"],
            },
        ),
    ]
