# Generated by Django 5.2.17 on 2026-09-15 23:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
        ("prontuarios", "0003_documento"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="anamnese",
            name="alimentacao",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="estomago_digestao",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="figado_vesicula",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="historico_saude",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="hormonal_ciclo",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="intestino",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="medicamentos",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="melasma_pele",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="observacoes_profissional",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="sinais_sintomas",
        ),
        migrations.RemoveField(
            model_name="anamnese",
            name="sono",
        ),
        migrations.AddField(
            model_name="anamnese",
            name="acantose_nigricans",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="acantose nigricans"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="acne",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="acne (região)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="acorda_cansada",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="acorda cansada"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="acorda_enjoada",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="acorda enjoada"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="acrocordons",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="acrocórdons"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="adenomiose",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="adenomiose"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="alcool",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="álcool (frequência/tipo)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="alergia_alimentar",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="alergia alimentar"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="alergias_bijuteria_perfume_produtos",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="alergias (bijuteria/perfume/produtos)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="almoco",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="almoço (preferências e horário)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="alteracoes_cardiacas",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="alterações cardíacas"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="alteracoes_psicologicas_psiquiatricas",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="alterações psicológicas/psiquiátricas",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="altura",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="altura (cm)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="ansiedade",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="ansiedade"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="antecedentes_alergicos",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="antecedentes alérgicos"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="antecedentes_oncologicos",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="antecedentes oncológicos (câncer de mama/ovário/endométrio)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="anticoncepcional",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="anticoncepcional (qual)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="apetite",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="apetite (pouco/muito)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="arrotos",
            field=models.CharField(blank=True, max_length=150, verbose_name="arrotos"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="azia_refluxo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="azia/refluxo"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="baixa_libido_hormonal",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="baixa libido"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="baixa_libido_saude_mental",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="baixa libido"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="cabelo_branco_precoce",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="cabelo branco precoce"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="cafe_da_manha",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="café da manhã (preferências e horário)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="cafe_da_tarde",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="café da tarde (preferências e horário)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="calcanhar_rachado",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="calcanhar rachado"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="candidiase_repeticao",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="candidíase de repetição"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="caspa",
            field=models.CharField(blank=True, max_length=150, verbose_name="caspa"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="celulite",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="celulite (região)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="cirurgias_previas",
            field=models.TextField(blank=True, verbose_name="cirurgias prévias"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="condicionador",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="condicionador"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="data_nascimento",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de nascimento"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="depressao_tristeza",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="depressão/tristeza"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="dermatite",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="dermatite"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="descontrole_alimentar",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="descontrole alimentar"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="desejo_doces_carboidratos",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="desejo por doces/carboidratos"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="desodorante",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="desodorante"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="desperta_madrugada",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="desperta entre 2h e 3h da manhã",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="despertares_noturnos",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="despertares noturnos"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="diabetes",
            field=models.CharField(blank=True, max_length=150, verbose_name="diabetes"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="diarreia",
            field=models.CharField(blank=True, max_length=150, verbose_name="diarreia"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="dificuldade_ganhar_peso",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="dificuldade de ganhar peso"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="digestao_proteinas",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="digestão de proteínas"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="distensao_abdominal",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="distensão abdominal"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="disturbio_circulatorio",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="distúrbio circulatório"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="disturbio_gastrointestinal",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="distúrbio gastrointestinal"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="disturbio_hormonal",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="distúrbio hormonal"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="disturbio_renal",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="distúrbio renal"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="doencas_metabolicas",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="doenças metabólicas (diabetes/hipertensão/dislipidemia)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="dor_de_cabeca",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="dor de cabeça"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="eliminacao_incompleta",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="eliminação incompleta"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="e-mail"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="endereco",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="endereço completo"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="endometriose",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="endometriose"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="epilepsia",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="epilepsia (frequência)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="esforco_evacuatorio",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="esforço evacuatório"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="estresse",
            field=models.CharField(blank=True, max_length=150, verbose_name="estresse"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="exposicao_solar",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="exposição solar"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="extremidades_frias",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="extremidades frias"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="fadiga",
            field=models.CharField(blank=True, max_length=150, verbose_name="fadiga"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="falta_de_energia",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="falta de energia"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="fezes_endurecidas_amolecidas",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="fezes (endurecidas/amolecidas)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="fluxo_menstrual",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="fluxo menstrual (intensidade/coágulos)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="foco_concentracao",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="foco/concentração"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="foto_rosto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="anamnese_fotos/%Y/%m/",
                verbose_name="foto do rosto",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="frequencia_exercicio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="frequência de exercício"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="frequencia_intestinal",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="frequência intestinal"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="gases",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="gases (frequência/cheiro)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="gestacoes",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="gestações"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="gestante",
            field=models.CharField(blank=True, max_length=100, verbose_name="gestante"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="gordura_localizada",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="gordura localizada"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="gosto_metalico",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="gosto metálico"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="hidradenite",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="hidradenite"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="hidratante",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="hidratante"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="hipo_hipertensao_arterial",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="hipo/hipertensão arterial"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="hipo_hipertireoidismo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="hipo/hipertireoidismo"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_acordar",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário de acordar"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_dormir",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário de dormir"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horas_dormidas",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horas dormidas"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="idade",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="idade_menarca",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="idade da menarca"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="inchaco_retencao",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="inchaço/retenção"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="infeccao_urinaria_repeticao",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="infecção urinária de repetição",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="ingestao_agua",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ingestão de água (copos/dia)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="insonia",
            field=models.CharField(blank=True, max_length=150, verbose_name="insônia"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="irritabilidade",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="irritabilidade"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="jantar",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="jantar (preferências e horário)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="maquiagem",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="maquiagem"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="marcapasso",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="marcapasso"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="marcas_dente_lingua",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="marcas de dente na língua"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="massa_muscular",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="massa muscular"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="mau_cheiro_suor_forte",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="mau cheiro / suor forte"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="mau_humor_raiva",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="mau humor/raiva"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="melasma",
            field=models.CharField(blank=True, max_length=150, verbose_name="melasma"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="memoria",
            field=models.CharField(blank=True, max_length=150, verbose_name="memória"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="menstruacao_atual",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="menstruação atual"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="multiplas_alergias",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="múltiplas alergias"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="orgaos_mais_atencao",
            field=models.TextField(
                blank=True,
                verbose_name="quais órgãos você sente que precisam de mais atenção?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="outras_doencas",
            field=models.TextField(blank=True, verbose_name="outras doenças"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="outros_sintomas_doencas",
            field=models.TextField(
                blank=True, verbose_name="você tem outros sintomas e/ou doenças?"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="pele_ressecada",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="pele ressecada"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="peso",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                verbose_name="peso (kg)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="pouco_suor_pos_treino",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="pouco suor pós-treino"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="preferencia_carne",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="preferência de carne (branca/vermelha)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="profissao",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="profissão"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="protetor_solar",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="protetor solar (marca/duração)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="psoriase",
            field=models.CharField(blank=True, max_length=150, verbose_name="psoríase"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="qualidade_sono",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="qualidade do sono"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="queda_de_cabelo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="queda de cabelo"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="queratose_pilar",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="queratose pilar"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="retirada_orgaos",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="retirada de órgãos"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="rosacea",
            field=models.CharField(blank=True, max_length=150, verbose_name="rosácea"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="rotina_matinal",
            field=models.TextField(blank=True, verbose_name="rotina matinal"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="sabonete",
            field=models.CharField(blank=True, max_length=150, verbose_name="sabonete"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="saburra_amarelada",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="saburra amarelada"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_emocional",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com seu equilíbrio emocional?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_energia",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com seu nível de energia?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_figado",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com sua disposição e bem-estar geral?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_hormonal",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com seu equilíbrio hormonal?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_intestino",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com o funcionamento do seu intestino?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_pele",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com sua pele?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_sono",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com a qualidade do seu sono?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="satisfacao_tratamentos_anteriores",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você está satisfeita com os resultados dos tratamentos anteriores?",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="sede_excessiva",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="sede excessiva"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="shampoo",
            field=models.CharField(blank=True, max_length=100, verbose_name="shampoo"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="sobrepeso_obesidade",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="sobrepeso/obesidade"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="sono_agitado_superficial",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="sono agitado/superficial"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="sop",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="SOP (síndrome dos ovários policísticos)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tabagismo",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="tabagismo (quantidade/dia)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="telefone",
            field=models.CharField(blank=True, max_length=20, verbose_name="telefone"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tempo_desde_ultimo_tratamento",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="tempo desde o último tratamento",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tempo_melasma_estabilizado",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="tempo que o melasma ficou estabilizado",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tipo_exercicio",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="tipo de exercício"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tipo_parto",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="tipo de parto"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tpm",
            field=models.CharField(blank=True, max_length=150, verbose_name="TPM"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tratamento_medico_atual",
            field=models.TextField(blank=True, verbose_name="tratamento médico atual"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="tratamentos_anteriores",
            field=models.TextField(
                blank=True, verbose_name="tratamentos anteriores (quais)"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="unhas_fracas",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="unhas fracas"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="urticaria",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="urticária"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="uso_medicamentos_controlados",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="uso de medicamentos controlados",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="vicio_em_doce",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="vício em doce"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="zumbido_vertigem",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="zumbido/vertigem"
            ),
        ),
        migrations.CreateModel(
            name="LinkAnamnese",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("preenchido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_anamnese",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "link de anamnese",
                "verbose_name_plural": "links de anamnese",
                "ordering": ["-criado_em"],
            },
        ),
    ]
