# Generated by Django 5.2.17 on 2026-09-16 14:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0003_organizacao_dias_lead_parado"),
        ("pacientes", "0002_paciente_cidade_paciente_profissao"),
        ("prontuarios", "0004_remove_anamnese_alimentacao_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LinkCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link_checkin",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "link de check-in",
                "verbose_name_plural": "links de check-in",
            },
        ),
        migrations.CreateModel(
            name="RegistroEvolucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[("PACIENTE", "Paciente"), ("PROFISSIONAL", "Equipe")],
                        default="PACIENTE",
                        max_length=12,
                    ),
                ),
                (
                    "evacuou",
                    models.CharField(
                        blank=True,
                        choices=[("SIM", "Sim"), ("NAO", "Não")],
                        max_length=3,
                        verbose_name="evacuou?",
                    ),
                ),
                (
                    "fezes_endurecidas",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SIM", "Sim"),
                            ("UM_POUCO", "Um pouco"),
                            ("NAO", "Não"),
                        ],
                        max_length=8,
                        verbose_name="fezes endurecidas?",
                    ),
                ),
                (
                    "evacuacao_completa",
                    models.CharField(
                        blank=True,
                        choices=[("SIM", "Sim"), ("NAO", "Não")],
                        max_length=3,
                        verbose_name="sensação de evacuação completa?",
                    ),
                ),
                (
                    "distensao_abdominal",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="distensão abdominal",
                    ),
                ),
                (
                    "plenitude_pos_comer",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="plenitude após comer",
                    ),
                ),
                (
                    "arrotos",
                    models.CharField(
                        blank=True,
                        choices=[("SIM", "Sim"), ("NAO", "Não")],
                        max_length=3,
                        verbose_name="arrotos?",
                    ),
                ),
                (
                    "dor_desconforto",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="dor ou desconforto",
                    ),
                ),
                (
                    "energia_acordar",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="energia ao acordar",
                    ),
                ),
                (
                    "energia_apos_almoco",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="energia após o almoço",
                    ),
                ),
                (
                    "energia_fim_dia",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="energia no final do dia",
                    ),
                ),
                (
                    "qualidade_sono",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="qualidade do sono",
                    ),
                ),
                (
                    "vezes_acordou_noite",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        verbose_name="quantas vezes acordou durante a noite?",
                    ),
                ),
                (
                    "horarios_acordou",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="em quais horários?"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registros_evolucao",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de evolução",
                "verbose_name_plural": "registros de evolução",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["paciente", "criado_em"],
                        name="prontuarios_pacient_c6a6a9_idx",
                    )
                ],
            },
        ),
    ]
