# Generated by Django 5.2.17 on 2026-09-16 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuarios", "0005_linkcheckin_registroevolucao"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_digestao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que a digestão melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_energia",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que a energia melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_intestino",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que o intestino melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_sono",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que o sono melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_digestao",
            field=models.TextField(blank=True, verbose_name="observação (digestão)"),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_energia",
            field=models.TextField(blank=True, verbose_name="observação (energia)"),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_intestino",
            field=models.TextField(blank=True, verbose_name="observação (intestino)"),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_sono",
            field=models.TextField(blank=True, verbose_name="observação (sono)"),
        ),
    ]
