# Generated by Django 5.2.17 on 2026-09-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuarios", "0006_registroevolucao_melhora_digestao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anamnese",
            name="ceia",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="o que consome na ceia"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="faz_cafe_da_tarde",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="faz café da tarde?"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="faz_ceia",
            field=models.CharField(blank=True, max_length=50, verbose_name="faz ceia?"),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_almoco",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário do almoço"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_cafe_da_manha",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário do café da manhã"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_cafe_da_tarde",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário do café da tarde"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_ceia",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário da ceia"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="horario_jantar",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="horário do jantar"
            ),
        ),
        migrations.AlterField(
            model_name="anamnese",
            name="almoco",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="o que consome no almoço"
            ),
        ),
        migrations.AlterField(
            model_name="anamnese",
            name="cafe_da_manha",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="o que consome no café da manhã",
            ),
        ),
        migrations.AlterField(
            model_name="anamnese",
            name="cafe_da_tarde",
            field=models.CharField(
                blank=True,
                max_length=255,
                verbose_name="o que consome no café da tarde",
            ),
        ),
        migrations.AlterField(
            model_name="anamnese",
            name="jantar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="o que consome no jantar"
            ),
        ),
    ]
