# Generated by Django 5.2.17 on 2026-09-19 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuarios", "0007_anamnese_ceia_anamnese_faz_cafe_da_tarde_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="registroevolucao",
            name="disposicao_geral",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="sua disposição geral hoje",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="equilibrio_emocional",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="seu equilíbrio emocional hoje",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="equilibrio_hormonal",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="seu equilíbrio hormonal hoje",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="estado_pele",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="como está sua pele hoje",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_disposicao",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que a disposição geral melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_emocional",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que o equilíbrio emocional melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_hormonal",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que o equilíbrio hormonal melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="melhora_pele",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="de 0 a 10, o quanto você sentiu que a pele melhorou hoje?",
            ),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_disposicao",
            field=models.TextField(blank=True, verbose_name="observação (disposição)"),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_emocional",
            field=models.TextField(blank=True, verbose_name="observação (emocional)"),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_hormonal",
            field=models.TextField(blank=True, verbose_name="observação (hormonal)"),
        ),
        migrations.AddField(
            model_name="registroevolucao",
            name="observacao_pele",
            field=models.TextField(blank=True, verbose_name="observação (pele)"),
        ),
    ]
