# Generated by Django 5.2.17 on 2026-09-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prontuarios", "0008_registroevolucao_disposicao_geral_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anamnese",
            name="cor_lingua",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="cor predominante da língua"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="cor_saburra",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="cor da saburra"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="feridas_lingua",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="feridas, aftas ou nódulos na língua/boca com mais de 15-20 dias",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="mau_halito_caseos",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="mau hálito ou cáseos amigdalianos",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="raspagem_lingua",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="raspa a língua em jejum"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="saburra_lingual",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="saburra lingual (presença/intensidade)",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="sensibilidade_lingua",
            field=models.CharField(
                blank=True,
                max_length=150,
                verbose_name="dor, queimação ou sensibilidade na língua/boca",
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="textura_lingua",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="textura da língua"
            ),
        ),
        migrations.AddField(
            model_name="anamnese",
            name="umidade_boca",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="umidade da boca"
            ),
        ),
    ]
