# Generated by Django 5.2.17 on 2026-09-13 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agenda", "0001_initial"),
        ("pacientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Servico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("valor_padrao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "serviço",
                "verbose_name_plural": "serviços (tabela de preços)",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Pagamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "Pix"),
                            ("DEBITO", "Cartão de débito"),
                            ("CREDITO", "Cartão de crédito"),
                            ("CONVENIO", "Convênio/plano de saúde"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("PAGO", "Pago"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                ("data_vencimento", models.DateField(blank=True, null=True)),
                ("data_pagamento", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "consulta",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagamentos",
                        to="agenda.consulta",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagamentos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "servico",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="financeiro.servico",
                    ),
                ),
            ],
            options={
                "verbose_name": "pagamento",
                "verbose_name_plural": "pagamentos",
                "ordering": ["-data_vencimento", "-criado_em"],
            },
        ),
    ]
