# Generated by Django 5.2.17 on 2026-09-13 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financeiro", "0001_initial"),
        ("programas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="acompanhamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Programa de acompanhamento ao qual este pagamento pertence, se houver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamentos",
                to="programas.acompanhamento",
            ),
        ),
    ]
