# Generated by Django 5.2.17 on 2026-09-14 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0002_organizacao_padrao_e_dados_iniciais"),
        ("financeiro", "0002_pagamento_acompanhamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamento",
            name="data_pagamento",
            field=models.DateField(
                blank=True,
                help_text="Preenchida automaticamente quando o valor total é quitado.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="forma_pagamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DINHEIRO", "Dinheiro"),
                    ("PIX", "Pix"),
                    ("DEBITO", "Cartão de débito"),
                    ("CREDITO", "Cartão de crédito"),
                    ("CONVENIO", "Convênio/plano de saúde"),
                    ("OUTRO", "Outro"),
                ],
                help_text="Preenchida automaticamente com a forma do recebimento mais recente.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("PARCIAL", "Parcial"),
                    ("PAGO", "Pago"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                help_text="Calculado automaticamente a partir dos recebimentos registrados.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pagamento",
            name="valor",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="valor total"
            ),
        ),
        migrations.CreateModel(
            name="Recebimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "forma_pagamento",
                    models.CharField(
                        choices=[
                            ("DINHEIRO", "Dinheiro"),
                            ("PIX", "Pix"),
                            ("DEBITO", "Cartão de débito"),
                            ("CREDITO", "Cartão de crédito"),
                            ("CONVENIO", "Convênio/plano de saúde"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("observacoes", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
                (
                    "pagamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recebimentos",
                        to="financeiro.pagamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "recebimento",
                "verbose_name_plural": "recebimentos",
                "ordering": ["-data", "-criado_em"],
            },
        ),
    ]
