# Generated by Django 5.2.17 on 2026-09-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contas", "0004_organizacao_saldo_inicial_financeiro"),
        ("financeiro", "0004_backfill_recebimentos_pagos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "banco",
                "verbose_name_plural": "bancos",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "grupo",
                    models.CharField(
                        choices=[
                            ("RECEITA_OPERACIONAL", "Receita Operacional"),
                            ("CUSTO_VARIAVEL", "Custo Variável"),
                            ("CUSTO_FIXO", "Custo Fixo"),
                            ("DESPESA_NAO_OPERACIONAL", "Despesa Não Operacional"),
                            ("RECEITA_NAO_OPERACIONAL", "Receita Não Operacional"),
                        ],
                        max_length=30,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "categoria financeira",
                "verbose_name_plural": "categorias financeiras",
                "ordering": ["grupo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Lancamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=255)),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[("PREVISTO", "Previsto"), ("REALIZADO", "Realizado")],
                        default="REALIZADO",
                        max_length=10,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "banco",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="financeiro.banco",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lancamentos",
                        to="financeiro.categoriafinanceira",
                    ),
                ),
                (
                    "organizacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contas.organizacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "lançamento",
                "verbose_name_plural": "lançamentos",
                "ordering": ["-data", "-criado_em"],
            },
        ),
        migrations.AddConstraint(
            model_name="banco",
            constraint=models.UniqueConstraint(
                fields=("organizacao", "nome"), name="banco_unico_por_organizacao"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriafinanceira",
            constraint=models.UniqueConstraint(
                fields=("organizacao", "nome"),
                name="categoria_financeira_unica_por_organizacao",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamento",
            index=models.Index(
                fields=["organizacao", "data"], name="financeiro__organiz_f6b1d6_idx"
            ),
        ),
    ]
