# Generated by Django 5.2.17 on 2026-09-24 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0004_venda_itemvenda"),
        ("financeiro", "0005_banco_categoriafinanceira_lancamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagamento",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                help_text="Compra de produto à qual este pagamento pertence, se houver.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pagamentos",
                to="estoque.venda",
            ),
        ),
    ]
