"""
Django settings for clinica project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Em produção, defina a variável de ambiente DJANGO_SECRET_KEY.
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-1c_9g1(5t8_-=d+xn2kf*bz7-=oit=w6$6@kg0^i=jzz$nhx2i",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    h for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h
]

# Domínios (com https://) autorizados a enviar formulários (proteção CSRF).
# Em produção, defina DJANGO_CSRF_TRUSTED_ORIGINS separado por vírgulas,
# ex.: https://minhaclinica.com.br,https://meuapp.up.railway.app
CSRF_TRUSTED_ORIGINS = [
    o for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o
]

# A maioria das hospedagens (Railway, Render...) termina o HTTPS num proxy e
# repassa a requisição por HTTP internamente, sinalizando o protocolo original
# neste cabeçalho. Sem isso, o Django acha que a conexão nunca é segura.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if not DEBUG:
    # Em produção (atrás de HTTPS), força conexão segura e cookies seguros.
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary_storage",
    "cloudinary",
    "contas",
    "leads",
    "core",
    "pacientes",
    "profissionais",
    "agenda",
    "programas",
    "prontuarios",
    "financeiro",
    "estoque",
]

AUTH_USER_MODEL = "contas.Usuario"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "core:home"
LOGOUT_REDIRECT_URL = "login"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "clinica.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "clinica.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Local/desenvolvimento: SQLite (arquivo único, zero configuração).
# Produção: defina a variável de ambiente DATABASE_URL (a maioria das
# hospedagens já provisiona isso automaticamente ao criar um banco Postgres,
# mas é preciso REFERENCIAR essa variável no serviço da aplicação — criar o
# banco sozinho não basta), ex.: postgres://usuario:senha@host:5432/nome

import dj_database_url

if not DEBUG and "DATABASE_URL" not in os.environ:
    # Em produção, cair para SQLite silenciosamente é o pior cenário possível:
    # o disco do container é descartado a cada deploy e todos os dados (
    # usuários, pacientes, leads...) somem sem aviso. Preferimos recusar subir
    # a fingir que está tudo bem.
    raise RuntimeError(
        "DJANGO_DEBUG=False mas a variável de ambiente DATABASE_URL não foi "
        "encontrada. Sem ela, o sistema usaria SQLite dentro do container e "
        "perderia todos os dados a cada novo deploy. Configure DATABASE_URL "
        "apontando para o Postgres (no Railway: aba Variables do serviço da "
        "aplicação → adicione uma referência à variável DATABASE_URL do "
        "serviço Postgres) antes de subir novamente."
    )

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Arquivos enviados pelos usuários (fotos de prova social, fotos de evolução,
# exames/documentos). O Railway apaga o disco do container a cada deploy, então
# em produção isso precisa ir pro Cloudinary — configurável por variáveis de
# ambiente. Sem essas variáveis (ex.: rodando localmente), cai de volta no
# disco local, sem exigir uma conta Cloudinary pra desenvolver.
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

CLOUDINARY_STORAGE = {
    "CLOUD_NAME": os.environ.get("CLOUDINARY_CLOUD_NAME", ""),
    "API_KEY": os.environ.get("CLOUDINARY_API_KEY", ""),
    "API_SECRET": os.environ.get("CLOUDINARY_API_SECRET", ""),
}

if CLOUDINARY_STORAGE["CLOUD_NAME"]:
    STORAGES["default"] = {"BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
